#!/usr/bin/env bash

SYSTEM=$(uname -s)

die() {
    echo >&2 "$@"
    exit 1
}

if [ ! -z ${INIT_TYPE} ] ; then
    SYSTEM=${INIT_TYPE}
fi

# Simplified dudeist daemonizer. Don't care about lock files, separate
# stdout/stderr and fancy stuff. #YOLO

case "${SYSTEM,,}" in
    linux)
        daemonize -p "${DAEMON_PID}" -e "${OUT_FILE}" -o "${OUT_FILE}" "$@"
        ;;
    freebsd)
        daemon -p "${DAEMON_PID}" -o "${OUT_FILE}" "$@"
        ;;
    systemd)
        systemctl start crowdsec || SYSTEMD_RUNNING=true
        ;;
    *)
        die "unsupported system: $SYSTEM"
        ;;
esac

